// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-5pYvJLoj9Lj3KhdBy-bOm-v-UxS-fHk',
    appId: '1:1011531909952:web:ef0f70a7ed970157fb48a5',
    messagingSenderId: '1011531909952',
    projectId: 'chat-app-38e26',
    authDomain: 'chat-app-38e26.firebaseapp.com',
    storageBucket: 'chat-app-38e26.firebasestorage.app',
    measurementId: 'G-EBZRNEW2VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqBPazAfOcz4Z94Y9fR3y11MvNRMGy7ZA',
    appId: '1:1011531909952:android:9d848e7a9ae96e7ffb48a5',
    messagingSenderId: '1011531909952',
    projectId: 'chat-app-38e26',
    storageBucket: 'chat-app-38e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgxhFS2SaxlESoGFjoM7TT4diC6iRnC0',
    appId: '1:1011531909952:ios:5561d992f8bd057afb48a5',
    messagingSenderId: '1011531909952',
    projectId: 'chat-app-38e26',
    storageBucket: 'chat-app-38e26.firebasestorage.app',
    iosBundleId: 'com.example.chatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhgxhFS2SaxlESoGFjoM7TT4diC6iRnC0',
    appId: '1:1011531909952:ios:5561d992f8bd057afb48a5',
    messagingSenderId: '1011531909952',
    projectId: 'chat-app-38e26',
    storageBucket: 'chat-app-38e26.firebasestorage.app',
    iosBundleId: 'com.example.chatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-5pYvJLoj9Lj3KhdBy-bOm-v-UxS-fHk',
    appId: '1:1011531909952:web:47f1430f9f42680cfb48a5',
    messagingSenderId: '1011531909952',
    projectId: 'chat-app-38e26',
    authDomain: 'chat-app-38e26.firebaseapp.com',
    storageBucket: 'chat-app-38e26.firebasestorage.app',
    measurementId: 'G-1Z7M40MS0K',
  );
}
